import Head from "next/head";
import { Inter } from "@next/font/google";
import Layout from "@/layouts/Layout";
import me from "../../public/assets/me.jpeg";
import { useContext } from "react";
import themeContext from "@/themeContext";
import Link from "next/link";

export default function Home() {
  const { isDarkTheme } = useContext(themeContext);
  return (
    <>
      <Head>
        <title>Tech Insider</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div
          className={`py-24 flex prose flex-col w-full prose-sm lg:prose-xl ${
            isDarkTheme ? "prose-invert" : ""
          }`}
        >
          <h1>Who am I?</h1>
          <div className="flex flex-between items-center w-full space-x-12">
            <img className="h-32 w-32 rounded-full" src={me.src} />
            <div>
              <p className="text-base">Federico Targa</p>
              <p className="text-base">21 years old</p>
              <p className="text-base">Chilling in the west Indies</p>
            </div>
          </div>
          <p>
            Hello and welcome to my tech blog! I&apos;m thrilled to be sharing
            my passion for web development and programming with you all. My name
            is <span className="text-gray-800 font-bold">Rick</span>, and I am a
            web developer and a true enthusiast of all things tech. I&apos;ve
            always been fascinated by the world of technology and how it has the
            power to make a positive impact on our daily lives. Through this
            blog, I want to share my experiences, projects, and insights with
            the wider tech community. Whether you&apos;re a beginner just
            starting out or a seasoned professional looking to learn something
            new, I hope to provide valuable and informative content that will
            inspire and encourage you in your own tech journey. So, sit back,
            grab a cup of coffee, and let&apos;s dive into the world of tech
            together! I can&apos;t wait to share my thoughts and ideas with you
            all.
          </p>
          <br />
          <Link
            rel="noreferrer"
            href="https://github.com/rickturner2001"
            type="button"
            className="w-max text-white dark:bg-white dark:hover:bg-gray-100 dark:text-[#24292F] visited:text-white visited:no-underline active:no-underline not-prose bg-[#24292F] no-underline hover:bg-[#24292F]/90 focus:ring-4 focus:outline-none focus:ring-[#24292F]/50 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:focus:ring-gray-500 dark:hover:bg-[#050708]/30 mr-2 mb-2"
            target="_blank"
          >
            <svg
              className="w-4 h-4 mr-2 -ml-1"
              aria-hidden="true"
              focusable="false"
              data-prefix="fab"
              data-icon="github"
              role="img"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 496 512"
            >
              <path
                fill="currentColor"
                d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3 .3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5 .3-6.2 2.3zm44.2-1.7c-2.9 .7-4.9 2.6-4.6 4.9 .3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3 .7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3 .3 2.9 2.3 3.9 1.6 1 3.6 .7 4.3-.7 .7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3 .7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3 .7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"
              ></path>
            </svg>
            Check out my Github
          </Link>
          <h2>My development stack</h2>
          <p>
            As a web developer, I have a strong focus on using{" "}
            <strong>Python</strong> and <strong>Typescript</strong> as my
            primary programming languages. These two languages have become
            essential in my toolkit and allow me to build powerful and scalable
            applications.
          </p>
          <p>
            For data analysis, I rely on libraries such as{" "}
            <strong>pandas</strong> and <strong>numpy</strong>, which make it
            easy to manipulate and analyze large datasets. When it comes to
            visualizing data, I prefer to use <strong>matplotlib</strong>, which
            provides a wide range of customizable plotting options.
          </p>
          <p>
            For the backend, I utilize the robust capabilities of{" "}
            <strong>Django</strong>, <strong>Flask</strong>, and
            <strong>FastAPI</strong>. These frameworks offer different
            approaches to building web applications, and I love using them for
            their versatility and performance.
          </p>
          <p>
            In addition to my main stack, I also enjoy using{" "}
            <strong>Next</strong> for building user-friendly and responsive
            frontend applications. I use <strong>Prisma</strong> and{" "}
            <strong>Trpc</strong>
            for building modern{" "}
            <span className="underline underline-offset-8 decoration-2 decoration-wavy decoration-red-500">
              typesafe
            </span>{" "}
            and scalable APIs, and <strong>Tailwind</strong>for styling my
            projects with ease.
          </p>
          <Link
            href="/articles"
            className="text-white not-prose no-underline visited:text-white text-center bg-gray-800 dark:bg-gray-100 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-4 mt-12 mr-2 mb-2 dark:hover:bg-gray-200 dark:focus:ring-gray-400 dark:border-gray-400 dark:text-gray-800"
          >
            Read articles
          </Link>
        </div>
      </Layout>
    </>
  );
}
